import { Roles } from "./constants";

export const exampleAdmin = {
  id: 1,
  name: "Admin",
  email: "admin@gmail",
  roles: [Roles.ADMIN],
};
export const exampleUsers = [
  {
    id: 1,
    name: "User 1",
    email: "example@gmail",
    roles: [Roles.USER, Roles.VENDOR],
  },
  {
    id: 2,
    name: "User 2",
    email: "example2@gmail",
    roles: [Roles.USER, Roles.VENDOR],
  },
  {
    id: 3,
    name: "User 3",
    email: "example3@gmail",
    roles: [Roles.USER, Roles.VENDOR],
  },
  {
    id: 4,
    name: "User 4",
    email: "example4@gmail",
    roles: [Roles.USER],
  },
  {
    id: 5,
    name: "User 5",
    email: "example5@gmail",
    roles: [Roles.USER],
  },
];
export const exampleServices = [
  {
    id: 1,
    title: "Service 1",
    professionalId: exampleUsers[0].id,
    description: "Description of service 1",
    price: 100,
    category: "Category 1",
    averageRating: 4.5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 2,
    title: "Service 2",
    professionalId: exampleUsers[0].id,
    description: "Description of service 2",
    category: "Category 2",
    price: 200,
    averageRating: 3,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 3,
    title: "Service 3",
    professionalId: exampleUsers[0].id,
    description: "Description of service 3",
    price: 300,
    category: "Category 3",
    averageRating: 2.5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 4,
    title: "Service 4",
    professionalId: exampleUsers[0].id,
    description: "Description of service 4",
    price: 400,
    category: "Category 4",
    averageRating: 4,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 5,
    title: "Service 5",
    professionalId: exampleUsers[0].id,
    description: "Description of service 5",
    price: 500,
    category: "Category 5",
    averageRating: 5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 6,
    title: "Service 6",
    professionalId: exampleUsers[0].id,
    description: "Description of service 6",
    price: 600,
    category: "Category 6",
    averageRating: 3.5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 7,
    title: "Service 7",
    professionalId: exampleUsers[0].id,
    description: "Description of service 7",
    price: 700,
    category: "Category 7",
    averageRating: 4.5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 8,
    title: "Service 8",
    professionalId: exampleUsers[0].id,
    description: "Description of service 8",
    price: 800,
    category: "Category 8",
    averageRating: 4.5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 9,
    title: "Service 9",
    professionalId: exampleUsers[0].id,
    description: "Description of service 9",
    price: 900,
    category: "Category 9",
    averageRating: 1.5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
  {
    id: 10,
    title: "Service 10",
    professionalId: exampleUsers[0].id,
    description: "Description of service 10",
    price: 1000,
    category: "Category 10",
    averageRating: 4.5,
    totalSolicitations: 10,
    totalReviews: 5,
    totalRatings: 5,
    totalComments: 5,
  },
];

export const ServiceReviews = [
  {
    id: 1,
    rating: 5,
    comment: "Good service",
    userId: exampleUsers[0].id,
    serviceId: exampleServices[0].id,
  },
];
